-- HutzellFlash global Top 10 leaderboard
-- Run once in Supabase Dashboard -> SQL Editor.
-- Safe to run again: tables/indexes/functions are created or replaced idempotently.

begin;

create extension if not exists pgcrypto;

create table if not exists public.hutzellflash_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  submitted_score bigint,
  run_seconds integer
);

create table if not exists public.hutzellflash_scores (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique references public.hutzellflash_runs(id) on delete restrict,
  initials text not null check (initials ~ '^[A-Z0-9]{3}$'),
  score bigint not null check (score >= 0),
  run_seconds integer not null check (run_seconds > 0),
  created_at timestamptz not null default now()
);

create index if not exists hutzellflash_scores_leaderboard_idx
  on public.hutzellflash_scores (score desc, created_at asc, id asc);

create index if not exists hutzellflash_runs_started_at_idx
  on public.hutzellflash_runs (started_at);

alter table public.hutzellflash_runs enable row level security;
alter table public.hutzellflash_scores enable row level security;

-- The browser never receives direct table access. Reads/writes happen only through
-- the SECURITY DEFINER RPC functions below.
revoke all on table public.hutzellflash_runs from anon, authenticated;
revoke all on table public.hutzellflash_scores from anon, authenticated;

create or replace function public.start_hutzellflash_run()
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_run_id uuid;
begin
  -- Clear abandoned/non-scoring run tokens while preserving every historical score.
  delete from public.hutzellflash_runs r
  where r.started_at < now() - interval '2 days'
    and not exists (
      select 1 from public.hutzellflash_scores s where s.run_id = r.id
    );

  insert into public.hutzellflash_runs default values
  returning id into v_run_id;

  return v_run_id;
end;
$$;

create or replace function public.get_hutzellflash_leaderboard()
returns table (
  leaderboard_rank integer,
  initials text,
  score bigint,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    row_number() over (order by s.score desc, s.created_at asc, s.id asc)::integer as leaderboard_rank,
    s.initials,
    s.score,
    s.created_at
  from public.hutzellflash_scores s
  order by s.score desc, s.created_at asc, s.id asc
  limit 10;
$$;

create or replace function public.submit_hutzellflash_score(
  p_run_id uuid,
  p_initials text,
  p_score bigint,
  p_run_seconds integer
)
returns table (
  accepted boolean,
  leaderboard_rank integer,
  cutoff_score bigint,
  message text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_run public.hutzellflash_runs%rowtype;
  v_initials text;
  v_elapsed numeric;
  v_cutoff bigint;
  v_score_id bigint;
  v_rank integer;
begin
  -- Serialize qualification checks so simultaneous submissions cannot both
  -- incorrectly claim the final Top 10 position.
  perform pg_advisory_xact_lock(841010);

  v_initials := upper(trim(coalesce(p_initials, '')));

  if v_initials !~ '^[A-Z0-9]{3}$' then
    raise exception 'Pilot name must be exactly 3 letters or numbers.';
  end if;

  if p_score is null or p_score < 0 then
    raise exception 'Invalid score.';
  end if;

  if p_run_seconds is null or p_run_seconds < 1 then
    raise exception 'Invalid run duration.';
  end if;

  select * into v_run
  from public.hutzellflash_runs
  where id = p_run_id
  for update;

  if not found then
    raise exception 'Invalid or expired run token.';
  end if;

  if v_run.completed_at is not null then
    raise exception 'This run has already been submitted.';
  end if;

  if v_run.started_at < now() - interval '2 hours' then
    raise exception 'This run token has expired.';
  end if;

  v_elapsed := extract(epoch from (now() - v_run.started_at));

  -- Client-reported flight time cannot exceed server-observed time. The small
  -- allowance covers request latency and countdown/frame rounding.
  if p_run_seconds > ceil(v_elapsed + 3) then
    raise exception 'Run timing failed validation.';
  end if;

  -- Lightweight anti-tamper ceiling. It is deliberately above legitimate
  -- maximum gameplay pace, but blocks trivial console submissions such as a
  -- million points after a five-second run.
  if p_score > (p_run_seconds::bigint * 1200 + 5000) then
    raise exception 'Score failed validation.';
  end if;

  -- Consume the run token even if the live board changed before submission.
  update public.hutzellflash_runs
  set completed_at = now(), submitted_score = p_score, run_seconds = p_run_seconds
  where id = p_run_id;

  select s.score into v_cutoff
  from public.hutzellflash_scores s
  order by s.score desc, s.created_at asc, s.id asc
  limit 1 offset 9;

  -- On a full board, a new score must strictly beat #10. Ties do not displace
  -- the player who reached that score first.
  if v_cutoff is not null and p_score <= v_cutoff then
    return query select false, null::integer, v_cutoff,
      'The leaderboard changed and this score no longer qualifies.'::text;
    return;
  end if;

  insert into public.hutzellflash_scores (run_id, initials, score, run_seconds)
  values (p_run_id, v_initials, p_score, p_run_seconds)
  returning id into v_score_id;

  select ranked.leaderboard_rank into v_rank
  from (
    select
      s.id,
      row_number() over (order by s.score desc, s.created_at asc, s.id asc)::integer as leaderboard_rank
    from public.hutzellflash_scores s
  ) ranked
  where ranked.id = v_score_id;

  select s.score into v_cutoff
  from public.hutzellflash_scores s
  order by s.score desc, s.created_at asc, s.id asc
  limit 1 offset 9;

  return query select true, v_rank, v_cutoff, 'Score posted.'::text;
end;
$$;

revoke all on function public.start_hutzellflash_run() from public;
revoke all on function public.get_hutzellflash_leaderboard() from public;
revoke all on function public.submit_hutzellflash_score(uuid, text, bigint, integer) from public;

grant execute on function public.start_hutzellflash_run() to anon, authenticated;
grant execute on function public.get_hutzellflash_leaderboard() to anon, authenticated;
grant execute on function public.submit_hutzellflash_score(uuid, text, bigint, integer) to anon, authenticated;

commit;
